### ISSUE TITLE
Shipping Box Design Spec

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/v2-Production#1]
- [x] Describe [Features of Shipping Box](#features)
- [x] Describe [Design of Shipping Box](#design)
- [x] Specify [Quality Test Criteria](#quality)
- [x] Specify [Drop Test Procedure](#drop-test)
- [x] @bcaswelch Check the design of the Shipping Box. We will use this design to ship your ViCase to you soon. The idea is that you can experience all final aspects of the product, including how it will arrive and look. This includes product and shipping box. → Bobby OK the design in a skype call.
# Follow up Tasks
- Design the shipping box
- Make movie of testing
- Write Article on Shipping Box. Publish on V²Site / ViSite. Purpose to inform about the product and to make buyers confident on shipping ViPC.
# Features of Shipping Box <a name="features"><a/>
- As light as possible to not add unnecessary shipping cost
- As protective as possible to ensure the encased product box does not get damaged during shipping
- **Re-usable for ViCase**. Retailer can receive ViCase, open it, inspect it, possibly add something to it, close it and ship to end user.
- **Re-usable for ViPC**. Retailer can receive ViCase, remove ViCase, assemble ViCase, insert ViCase into very same product box and shipping box
- Environmentally friendly
- Shock absorption. Good enough to ship mounted CPU cooler in ViPC.
- No print on shipping. This were requests from retailers in the past. If you can see on the outside that there is a cool product on the inside, then they experienced more loss in shipments.
- Space for shipping cooler with ViCase
- Include Cooler Stabilizer material for ViCase-Cooler-L and ViCase-Cooler-XL
# Reusable Flat ViCase Shipping Box

This is an experimental feature. Can we get the best of both worlds:
1. Flat shipping box when shipping ViCase
2. Reuse the same shipping box, but design it so that it has two heights and as such it can also contain the taller ViPC.
# Design of Shipping Box <a name="design"><a/>
- Swimming Product Box in Shipping Box design
- 6 EPE corner buffer plus 2 diagonal strips for top and bottom
# Quality Test Criteria <a name="quality"><a/>
# Drop Test Procedure <a name="drop-test"><a/>
## Testing Shipping of ViCase
1. Package ViCase
2. Perform Drop Tests
3. Unpack ViCase
4. Inspect for visual damages to Shipping Box, Product Box, ViCase
5. Especially check for dislodged cooler
### Distance and Floor
- Drop to concrete floor
- Drop distance is 1 m (3 feet)
### Number of drops
- 14 drops total: 6 sides, 8 corners
### Drop and test procedure
1. Make one drop
2. Unpack and perform all inspections and test
3. Pack again, drop again, repeat until all tests passed
### Kick tests
1. Place shipping box with product on the ground
2. Play football
3. Unpack and perform all inspections and test
### Video Recording
- Make a Video Recording of all tests
- Edit to a Video. The idea is to show 
  - that after a shipment torture the ViCase is intact
  - how much care we put into one detail, such as shipping box. This is but one example of the care we put into any detail. Thus, expect ViCase / ViPC is a great experience for you.

**Comment by georgillies** [comment]
Reusability: Good idea. Unless shipping is much cheaper for folded shipping box and ViCase. Video may be of lower priority.

**Comment by VillageHubertChen** [comment]
# Feedback to Georg's comment

Agreed. Meanwhile we had an idea for a → "Reusable Flat ViCase Shipping Box". Please check the added description in the original post. So we may be able to enjoy the best of both worlds.

As for the Video: We will film it when we make the tests. We will edit and publish it later when we have time. Filming during testing without audio should not be much effort and will be hard to redo later. I still believe once published that this will solve a lot of concerns of people who will buy a $ 2000 US computer from a small new online shop. Most new shops do not know who to package an assembled PC properly to survive shipping.

**Comment by VillageHubertChen** [comment]
# Feedback from Xiao Mao
1. By the time the retailer receives the shipment from china, the shipping box will have shipping marks and lots of stickers and packaging tape. Reusing this shipping box will make it look very torn when it arrives to the customer. We should prepare the customer for it so he is not surprised. That said, the shipping box will do its duty just fine, which is to protect the product box and the product. Reusing this box is more environmentally friendly than buying a new shipping box.
2. We need to place a separation sheet between each aluminum sheet to avoid scratches during shipping
