### ISSUE TITLE
New Method of Management Production

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/v2-Production#32]
- [x] HC: Analyze the good and bad after 3 weeks using Kanban Board for Production
- [x] HC: As result I created a dedicated Kanban board → https://waffle.io/V-Squared/v2-Production
- [x] HC: Document new system and why it should work
- [x] ML: Understanding and testing the new method: Read this Issue and try the new board
  - If OK: Create comment with: "Read, understood and agreed"
  - If not OK: Write your problems into the comment and trigger me to follow up
# Good and Bad first implementation using Kanban Board in Production
## Good
- Integration of management production with the rest of our activities
- Monday Morning Kick Off Meeting and daily stand-ups are possible
## Bad
- Still no good overview
- It is not possible to order issues other than in creation, which is not good enough
# Additional Production Kanban board
- https://waffle.io/V-Squared/v2-Production
- Making ViCase Golden Sample is clearly structured into 4 stages
- The order of cards can be changed within each stage column by simple drag & drop
- The first Kanban Board is used for Agile Meetings of V² → https://waffle.io/V-Squared/V-Squared.github.io
- The new Kanban Board is used to manage Production → https://waffle.io/V-Squared/v2-Production

**Comment by VillageMichaelLin** [comment]
Read, understood and agreed
