### ISSUE TITLE
M: Design change to fit DC-Jack-PCB for HDPLEX 250W DC-DC

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/v2-Production#48]
- [x] Document problem → see below
- [x] Brainstorm if this problem can be solved → yes, see below
- [x] determine joint mounting hole Ø → 8.5 mm
- [x] Check polarity: HDPLEX states in data sheet that the center pin is GND. This must be a mistake. We checked several labels of suggested PSU and they all have center pin to be plus. It is important for outside cylinder to be GND, as it could touch the case, which is GND too.
- [x] Draw DC-Jack-PCB for HDPLEX 250W DC-DC
- [x] Which type DC input PCB did V²Shop-Midwest get?
- [x] Place DC-Jack-PCB for HDPLEX 250W DC-DC into Issue to get V²Shop-Midwest to double check the dimensions
- [x] Change Rear Panel Design
- [x] Change all Production documentation for 2 mm part
# Gating

This design need to be made to complete creating manufacturing documentation for 2 mm parts.
# Problem to solve

The DC Cable jack is not a screw in but a very big PCB:

Big Type
![](http://www.hd-plex.com/images/product/250WDCATX/packagecontent/250wpackage6.jpg)

Small Type
![](http://www.hd-plex.com/images/product/250WDCATX/gallery/250Wgallery8.jpg)

![](http://www.hd-plex.com/images/product/250WDCATX/techspec/HDPLEX250WDCATXDIAGRAM.png)
# References
- http://www.hd-plex.com/product/250W.DC-ATX.PSU/en/fanlesspcpackagecontent.html
- http://www.hd-plex.com/product/250W.DC-ATX.PSU/en/fanlesspctechspec.html

**Comment by VillageHubertChen** [comment]
# Guessed PCB design, showing to tight fit

![250w-dc-dc-inputpowerpcb-snap-too-tight](https://cloud.githubusercontent.com/assets/7278716/16141070/0ed3a324-348a-11e6-9d58-f5244fc9a390.jpg)

**Comment by VillageHubertChen** [comment]
@bcaswelch 

# List of Questions to HD-Plex
- [x] Do they ship the small or big version of DC Jack PCB, see pictures above
  - do they have two options available?
  - can they do the solder in version for us?
- [x] Why shipping takes so long
- [x] What is average lead time on buying Power Supplies from HD-Plex? How much inventory do they usually keep?

Answers see below comment

**Comment by bcaswelch** [comment]
Good news- The small type is the one I received.

**Comment by VillageHubertChen** [comment]
@bcaswelch Great! However we still must have the answers to the questions above: [List of Questions to HD-Plex](#issuecomment-226680737)

**Comment by bcaswelch** [comment]
Email reply:

Hi Robert
1. You mean the 7.4_5.0 PCB for DC input?  Yes this is soldered onto PCB for mounting purpose since there is no self lock DC input for 7.4_5.0.
2. No,  this delay is caused by waiting for the the new version of 160AC-DC which is much more robust. Future orders will be shipped within 24 hours. 
3. I expected to have more than 100pcs of 160AC-DC and 250W DC-ATX starting from next month.  
   Larry

**Comment by VillageHubertChen** [comment]
@bcaswelch Great! Did you informed them on our project?

**Comment by bcaswelch** [comment]
No, I can reply to him and give details on it. Say that we are developing a computer case and plan to integrate hdplex power supply dimensions?

**Comment by VillageHubertChen** [comment]
I think it is needed. He said he got the new 160W. It is great that it is better. But what if it is different? The one you got is from Amazon and old version or is it from HDPlex and new version?

In any event it would be good if they could check our drawings to see if they know they will make changes to some dimensions within this year. Knowing that before hand we can change the ViCase accordingly. Otherwise you may face the problem that next shipment of their PSU will not be possible to mount in ViCase.

**Comment by bcaswelch** [comment]
Ok, I'll ask them about it. I got the new one and it appears the same, I guess just with higher quality parts. Thats why it took so long to ship it out.

**Comment by VillageHubertChen** [comment]
OK. Got it. I think we now have all information to complete this design. Thanks for all the follow up. You removed the gating from this issue. I will still keep the label until michael can complete the design.

**Comment by VillageHubertChen** [comment]
@VillageMichaelLin Bobby and me believe we have answered all your open questions in the conversation above. Please check it out and complete the design. Please update → [Issue > V-Squared > Evaluate HD-Plex PSU #132 ](https://github.com/V-Squared/V-Squared.github.io/issues/132) accordingly.

**Comment by bcaswelch** [comment]
Sounds good.

**Comment by VillageHubertChen** [comment]
@bcaswelch Then your job is done here. We take over from here. Thanks so much!
